(() => {
  function createAppState({ unit = "м", unitSystem = "metric", detectionSensitivity }) {
    return {
      image: null,
      imageSrc: "",
      imageName: "",
      backgroundVisible: true,
      backgroundOpacity: 1,
      previousBackgroundOpacity: 1,
      scale: 1,
      homeScale: 1,
      offsetX: 0,
      offsetY: 0,
      segments: [],
      polygons: [],
      referenceId: null,
      referencePixelLength: null,
      selectedSegmentIds: new Set(),
      selectedPolygonIds: new Set(),
      referenceValue: "",
      referenceValueMeters: null,
      unit,
      unitSystem,
      footnotesVisible: true,
      measurementPrecision: 3,
      footnoteSize: "normal",
      showUnitsInFootnotes: true,
      pendingPoint: null,
      polygonPoints: [],
      polygonPreviewPoint: null,
      polygonCloseTarget: null,
      isDragging: false,
      dragStart: null,
      didDrag: false,
      interactionMode: null,
      selectionBox: null,
      labelBounds: new Map(),
      polygonLabelBounds: new Map(),
      snapPoint: null,
      previewPoint: null,
      orthogonalGuide: null,
      alignmentGuide: null,
      rightAngleHints: [],
      rightAngleIds: new Set(),
      detectedSegments: [],
      smartGridEnabled: true,
      nextActionPromptVisible: false,
      workflowMode: null,
      detectionSensitivity,
      isEditingReferenceLength: false,
      isDrawingSegments: false,
      isDrawingArea: false,
      isChoosingBase: false,
      sidebarCollapsed: true,
      isSpacePressed: false,
      isAnalyzing: false,
      hoveredSegmentId: null,
      pendingReferenceId: null,
      lastPointerUpAt: 0,
    };
  }

  window.PlanScaleState = {
    createAppState,
  };
})();
